// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// matCov
SEXP matCov(const arma::mat A, const arma::mat B, const bool corMat);
RcppExport SEXP _MatrixOps_matCov(SEXP ASEXP, SEXP BSEXP, SEXP corMatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type B(BSEXP);
    Rcpp::traits::input_parameter< const bool >::type corMat(corMatSEXP);
    rcpp_result_gen = Rcpp::wrap(matCov(A, B, corMat));
    return rcpp_result_gen;
END_RCPP
}
// projDecomp
SEXP projDecomp(const arma::mat X, const arma::mat Y);
RcppExport SEXP _MatrixOps_projDecomp(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(projDecomp(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// fitOLS
SEXP fitOLS(const arma::colvec y, const arma::mat X);
RcppExport SEXP _MatrixOps_fitOLS(SEXP ySEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(fitOLS(y, X));
    return rcpp_result_gen;
END_RCPP
}
// fitWLS
SEXP fitWLS(const arma::vec y, const arma::mat X, const arma::vec w);
RcppExport SEXP _MatrixOps_fitWLS(SEXP ySEXP, SEXP XSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(fitWLS(y, X, w));
    return rcpp_result_gen;
END_RCPP
}
// norm
SEXP norm(const arma::vec x, const int p);
RcppExport SEXP _MatrixOps_norm(SEXP xSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< const int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(norm(x, p));
    return rcpp_result_gen;
END_RCPP
}
// matDet
SEXP matDet(const arma::mat A, const bool logDet);
RcppExport SEXP _MatrixOps_matDet(SEXP ASEXP, SEXP logDetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< const bool >::type logDet(logDetSEXP);
    rcpp_result_gen = Rcpp::wrap(matDet(A, logDet));
    return rcpp_result_gen;
END_RCPP
}
// matInv
SEXP matInv(const arma::mat A);
RcppExport SEXP _MatrixOps_matInv(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(matInv(A));
    return rcpp_result_gen;
END_RCPP
}
// matIP
SEXP matIP(const arma::mat A, const arma::mat B);
RcppExport SEXP _MatrixOps_matIP(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(matIP(A, B));
    return rcpp_result_gen;
END_RCPP
}
// MMP
SEXP MMP(const arma::mat A, const arma::mat B);
RcppExport SEXP _MatrixOps_MMP(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(MMP(A, B));
    return rcpp_result_gen;
END_RCPP
}
// matOP
SEXP matOP(const arma::mat A, const arma::mat B);
RcppExport SEXP _MatrixOps_matOP(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(matOP(A, B));
    return rcpp_result_gen;
END_RCPP
}
// matQF
SEXP matQF(const arma::mat X, const arma::mat A);
RcppExport SEXP _MatrixOps_matQF(SEXP XSEXP, SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(matQF(X, A));
    return rcpp_result_gen;
END_RCPP
}
// SchurC
SEXP SchurC(const arma::mat Ibb, const arma::mat Iaa, const arma::mat Iba);
RcppExport SEXP _MatrixOps_SchurC(SEXP IbbSEXP, SEXP IaaSEXP, SEXP IbaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type Ibb(IbbSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type Iaa(IaaSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type Iba(IbaSEXP);
    rcpp_result_gen = Rcpp::wrap(SchurC(Ibb, Iaa, Iba));
    return rcpp_result_gen;
END_RCPP
}
// tr
SEXP tr(const arma::mat A);
RcppExport SEXP _MatrixOps_tr(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(tr(A));
    return rcpp_result_gen;
END_RCPP
}
// logSumExp
SEXP logSumExp(const arma::vec x, const bool cum);
RcppExport SEXP _MatrixOps_logSumExp(SEXP xSEXP, SEXP cumSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< const bool >::type cum(cumSEXP);
    rcpp_result_gen = Rcpp::wrap(logSumExp(x, cum));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MatrixOps_matCov", (DL_FUNC) &_MatrixOps_matCov, 3},
    {"_MatrixOps_projDecomp", (DL_FUNC) &_MatrixOps_projDecomp, 2},
    {"_MatrixOps_fitOLS", (DL_FUNC) &_MatrixOps_fitOLS, 2},
    {"_MatrixOps_fitWLS", (DL_FUNC) &_MatrixOps_fitWLS, 3},
    {"_MatrixOps_norm", (DL_FUNC) &_MatrixOps_norm, 2},
    {"_MatrixOps_matDet", (DL_FUNC) &_MatrixOps_matDet, 2},
    {"_MatrixOps_matInv", (DL_FUNC) &_MatrixOps_matInv, 1},
    {"_MatrixOps_matIP", (DL_FUNC) &_MatrixOps_matIP, 2},
    {"_MatrixOps_MMP", (DL_FUNC) &_MatrixOps_MMP, 2},
    {"_MatrixOps_matOP", (DL_FUNC) &_MatrixOps_matOP, 2},
    {"_MatrixOps_matQF", (DL_FUNC) &_MatrixOps_matQF, 2},
    {"_MatrixOps_SchurC", (DL_FUNC) &_MatrixOps_SchurC, 3},
    {"_MatrixOps_tr", (DL_FUNC) &_MatrixOps_tr, 1},
    {"_MatrixOps_logSumExp", (DL_FUNC) &_MatrixOps_logSumExp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_MatrixOps(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
