# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Covariance
#' 
#' Calculates the correlation between two vectors.
#' 
#' @param A NxP matrix.
#' @param B NxQ matrix.
#' @param corMat Return correlation matrix?
#' @export
#' @return Numeric matrix. 
matCov <- function(A, B, corMat = FALSE) {
    .Call(`_MatrixOps_matCov`, A, B, corMat)
}

#' Projection Decomposition
#' 
#' Decomposes matrix \eqn{Y} into the projection onto the image of \eqn{X},
#' and the projection onto the orthogonal complement of the image. 
#' 
#' @param X NxP Numeric matrix.
#' @param Y NxQ Numeric matrix.
#' @return List containing the following:
#' \item{Coord}{Coordinates of the projection w.r.t. X.}
#' \item{Para}{Projection onto the image of X.}
#' \item{Ortho}{Projection onto the orthogonal complement.}
projDecomp <- function(X, Y) {
    .Call(`_MatrixOps_projDecomp`, X, Y)
}

#' Ordinary Least Squares
#' 
#' Fits the standard OLS model.
#' 
#' @param y Nx1 Numeric vector.
#' @param X NxP Numeric matrix.
#' 
#' @return List containing the following:
#' \item{Beta}{Regression coefficient.}
#' \item{V}{Outcome variance.}
#' \item{Ibb}{Information matrix for beta.}
#' \item{Resid}{Outcome residuals.}
#' @export
fitOLS <- function(y, X) {
    .Call(`_MatrixOps_fitOLS`, y, X)
}

#' Weighted Least Squares
#' 
#' Fits the following weighted least squares model: 
#' \eqn{y_{i}=x_{i}'\beta+\epsilon_{i}}. Here, the subject-specific residual is
#' normally distributed with mean zero and variance \eqn{\sigma^{2}/w_{i}}.
#' \eqn{w_{i}} is a known, subject-specific weight, and \eqn{\sigma} is a
#' common scale parameter.
#' 
#' @param y Nx1 Response vector.
#' @param X NxP Design matrix.
#' @param w Nx1 Weight vector.
#' @export
#' 
#' @return List containing the following:
#' \item{Beta}{Regression coefficient.}
#' \item{V}{Outcome variance.}
#' \item{Ibb}{Information matrix for beta.}
#' \item{Resid}{Outcome residuals.}
#'
fitWLS <- function(y, X, w) {
    .Call(`_MatrixOps_fitWLS`, y, X, w)
}

#' Matrix Determinant
#'
#' Calculates the determinant of \eqn{A}.
#'
#' @param A Numeric matrix.
#' @param logDet Return the logarithm of the determinant? 
#' @return Scalar. 
#' @export 
matDet <- function(A, logDet = FALSE) {
    .Call(`_MatrixOps_matDet`, A, logDet)
}

#' Matrix Inverse
#' 
#' Calcualtes \eqn{A^{-1}}.
#'
#' @param A Numeric matrix.
#' @return Numeric matrix. 
#' @export 
matInv <- function(A) {
    .Call(`_MatrixOps_matInv`, A)
}

#' Matrix Inner Product
#'
#' Calculates the product \eqn{A'B}.
#'
#' @param A Numeric matrix.
#' @param B Numeric matrix.
#' @return Numeric matrix.
#' @export 
matIP <- function(A, B) {
    .Call(`_MatrixOps_matIP`, A, B)
}

#' Matrix Matrix Product
#'
#' Calculates the product \eqn{AB}. 
#'
#' @param A Numeric matrix.
#' @param B Numeric matrix.
#' @return Numeric matrix.
#' @export  
MMP <- function(A, B) {
    .Call(`_MatrixOps_MMP`, A, B)
}

#' Matrix Outer Product
#' 
#' Calculates the outer product \eqn{AB'}.
#' 
#' @param A Numeric matrix.
#' @param B Numeric matrix.
#' @return Numeric matrix.
#' @export 
matOP <- function(A, B) {
    .Call(`_MatrixOps_matOP`, A, B)
}

#' Quadratic Form
#' 
#' Calculates the quadratic form \eqn{X'AX}.
#' 
#' @param X Numeric matrix.
#' @param A Numeric matrix.
#' @return Numeric matrix.
#' @export 
matQF <- function(X, A) {
    .Call(`_MatrixOps_matQF`, X, A)
}

#' Schur complement
#'
#' Calculates the efficient information \eqn{I_{bb}-I_{ba}I_{aa}^{-1}I_{ab}}. 
#'
#' @param Ibb Information of target parameter
#' @param Iaa Information of nuisance parameter
#' @param Iba Cross information between target and nuisance parameters
#' @return Numeric matrix. 
#' @export 
SchurC <- function(Ibb, Iaa, Iba) {
    .Call(`_MatrixOps_SchurC`, Ibb, Iaa, Iba)
}

#' Matrix Trace
#'
#' Calculates the trace of a matrix \eqn{A}.
#'
#' @param A Numeric matrix.
#' @return Scalar.
#' @export 
tr <- function(A) {
    .Call(`_MatrixOps_tr`, A)
}

