# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Correlation
#' 
#' Calculates the correlation between two vectors.
#' 
#' @param A First matrix.
#' @param B Second matrix.
#' @param cor Return correlation matrix?
#' @export
#' @return Numeric matrix. 
cov <- function(A, B, cor = FALSE) {
    .Call('_MatrixOps_cov', PACKAGE = 'MatrixOps', A, B, cor)
}

#' Linear Projection
#' 
#' Decomposes matrix \eqn{Y} into the projection onto the image of \eqn{X},
#' and the projection onto the orthogonal complement of the image. 
#' 
#' @param X Numeric matrix.
#' @param Y Numeric matrix.
#' @export
#' 
#' @return List containing the following:
#' \item{Coord}{Coordinates of the projection w.r.t. X.}
#' \item{Para}{Projection onto the image of X.}
#' \item{Ortho}{Projection onto the orthogonal complement.}
linProj <- function(X, Y) {
    .Call('_MatrixOps_linProj', PACKAGE = 'MatrixOps', X, Y)
}

#' Univariate OLS model.
#' 
#' Fits the standard OLS model.
#' 
#' @param y Outcome.
#' @param X Model matrix.
#' @export 
#' 
#' @return List containing the following:
#' \item{Beta}{Regression coefficient.}
#' \item{V}{Outcome variance.}
#' \item{Ibb}{Information matrix for beta.}
#' \item{Resid}{Outcome residuals.}
#' 
fitOLS <- function(y, X) {
    .Call('_MatrixOps_fitOLS', PACKAGE = 'MatrixOps', y, X)
}

#' Matrix Trace
#'
#' Calculates the trace of a matrix \eqn{A}.
#'
#' @param A Numeric matrix.
#' @return Scalar.
#' @export  
tr <- function(A) {
    .Call('_MatrixOps_tr', PACKAGE = 'MatrixOps', A)
}

#' Matrix Matrix Product
#'
#' Calculates the product \eqn{AB}. 
#'
#' @param A Numeric matrix.
#' @param B Numeric matrix.
#' @return Numeric matrix. 
#' @export 
MMP <- function(A, B) {
    .Call('_MatrixOps_MMP', PACKAGE = 'MatrixOps', A, B)
}

#' Matrix Inner Product
#'
#' Calculates the product \eqn{A'B}.
#'
#' @param A Numeric matrix.
#' @param B Numeric matrix.
#' @return Numeric matrix. 
#' @export 
matIP <- function(A, B) {
    .Call('_MatrixOps_matIP', PACKAGE = 'MatrixOps', A, B)
}

#' Matrix Inverse
#' 
#' Calcualtes \eqn{A^{-1}}.
#'
#' @param A Numeric matrix.
#' @return Numeric matrix. 
#' @export 
matInv <- function(A) {
    .Call('_MatrixOps_matInv', PACKAGE = 'MatrixOps', A)
}

#' Matrix Determinant
#'
#' Calculates the determinant of \eqn{A}.
#'
#' @param A Numeric matrix.
#' @return Scalar. 
#' @export 
det <- function(A) {
    .Call('_MatrixOps_det', PACKAGE = 'MatrixOps', A)
}

#' Fast Outer Product
#' 
#' Calculates the outer product \eqn{XY'}.
#' 
#' @param X Numeric matrix.
#' @param Y Numeric matrix.
#' @return Numeric matrix.
#' @export 
matOP <- function(X, Y) {
    .Call('_MatrixOps_matOP', PACKAGE = 'MatrixOps', X, Y)
}

#' Quadratic Form
#' 
#' Calculates the quadratic form \eqn{X'AX}.
#' 
#' @param X Numeric matrix.
#' @param A Numeric matrix.
#' @return Numeric matrix. 
#' @export 
matQF <- function(X, A) {
    .Call('_MatrixOps_matQF', PACKAGE = 'MatrixOps', X, A)
}

#' Schur complement
#'
#' Calculates the efficient information \eqn{I_{bb}-I_{ba}I_{aa}^{-1}I_{ab}}. 
#'
#' @param Ibb Information of target parameter
#' @param Iaa Information of nuisance parameter
#' @param Iba Cross information between target and nuisance parameters
#' @return Numeric matrix. 
#' @export 
SchurC <- function(Ibb, Iaa, Iba) {
    .Call('_MatrixOps_SchurC', PACKAGE = 'MatrixOps', Ibb, Iaa, Iba)
}

