# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Covariance
#' 
#' Calculates the correlation between two vectors.
#' 
#' @param A NxP matrix.
#' @param B NxQ matrix.
#' @param corMat Return correlation matrix?
#' @export
#' @return Numeric matrix. 
MatCov <- function(A, B, corMat = FALSE) {
    .Call(`_MatrixOps_MatCov`, A, B, corMat)
}

#' Eigenvalues of Symmetric Matrix. 
#' 
#' Calculates the eigenvalues of a symmetric matrix. 
#' 
#' @param A symmetric matrix. 
#' 
#' @export
#' 
#' @return Numeric vector.
EigSym <- function(A) {
    .Call(`_MatrixOps_EigSym`, A)
}

#' Ordinary Least Squares
#' 
#' Fits the standard OLS model.
#' 
#' @param y Nx1 Numeric vector.
#' @param X NxP Numeric matrix.
#' 
#' @return List of model components.
#' @export
FitOLS <- function(y, X) {
    .Call(`_MatrixOps_FitOLS`, y, X)
}

#' Weighted Least Squares
#' 
#' Fits the following weighted least squares model: 
#' \eqn{y_{i}=x_{i}'\beta+\epsilon_{i}}. Here, the subject-specific residual is
#' normally distributed with mean zero and variance \eqn{\sigma^{2}/w_{i}}.
#' \eqn{w_{i}} is a known, subject-specific weight, and \eqn{\sigma} is a
#' common scale parameter.
#' 
#' @param y Nx1 Response vector.
#' @param X NxP Design matrix.
#' @param w Nx1 Weight vector.
#' 
#' @return List of model components.
#' @export
FitWLS <- function(y, X, w) {
    .Call(`_MatrixOps_FitWLS`, y, X, w)
}

#' Lp Norm
#'
#' Calculates the Lp norm of a vector
#' 
#' @param x Jx1 numeric vector.
#' @param p scalar power. 
#'
#' @return Scalar norm.
#' @export 
Norm <- function(x, p = 2L) {
    .Call(`_MatrixOps_Norm`, x, p)
}

#' Matrix Determinant
#'
#' Calculates the determinant of \eqn{A}.
#'
#' @param A Numeric matrix.
#' @param logDet Return the logarithm of the determinant? 
#' @return Scalar. 
#' @export 
MatDet <- function(A, logDet = FALSE) {
    .Call(`_MatrixOps_MatDet`, A, logDet)
}

#' Matrix Inverse
#' 
#' Calcualtes \eqn{A^{-1}}.
#'
#' @param A Numeric matrix.
#' @return Numeric matrix. 
#' @export 
MatInv <- function(A) {
    .Call(`_MatrixOps_MatInv`, A)
}

#' Matrix Inner Product
#'
#' Calculates the product \eqn{A'B}.
#'
#' @param A Numeric matrix.
#' @param B Numeric matrix.
#' @return Numeric matrix.
#' @export 
MatIP <- function(A, B) {
    .Call(`_MatrixOps_MatIP`, A, B)
}

#' Matrix Matrix Product
#'
#' Calculates the product \eqn{AB}. 
#'
#' @param A Numeric matrix.
#' @param B Numeric matrix.
#' @return Numeric matrix.
#' @export  
MatProd <- function(A, B) {
    .Call(`_MatrixOps_MatProd`, A, B)
}

#' Matrix Outer Product
#' 
#' Calculates the outer product \eqn{AB'}.
#' 
#' @param A Numeric matrix.
#' @param B Numeric matrix.
#' @return Numeric matrix.
#' @export 
MatOP <- function(A, B) {
    .Call(`_MatrixOps_MatOP`, A, B)
}

#' Quadratic Form
#' 
#' Calculates the quadratic form \eqn{X'AX}.
#' 
#' @param X Numeric matrix.
#' @param A Numeric matrix.
#' @return Numeric matrix.
#' @export 
MatQF <- function(X, A) {
    .Call(`_MatrixOps_MatQF`, X, A)
}

#' Schur complement
#'
#' Calculates the efficient information \eqn{I_{bb}-I_{ba}I_{aa}^{-1}I_{ab}}. 
#'
#' @param Ibb Information of target parameter
#' @param Iaa Information of nuisance parameter
#' @param Iba Cross information between target and nuisance parameters
#' @return Numeric matrix. 
#' @export 
SchurC <- function(Ibb, Iaa, Iba) {
    .Call(`_MatrixOps_SchurC`, Ibb, Iaa, Iba)
}

#' Matrix Trace
#'
#' Calculates the trace of a matrix \eqn{A}.
#'
#' @param A Numeric matrix.
#' @return Scalar.
#' @export 
Tr <- function(A) {
    .Call(`_MatrixOps_Tr`, A)
}

#' Log Sum Exp
#'
#' Calculates the Jx1 log sum exp vector. 
#' 
#' @param x Jx1 numeric vector.
#' @param cum Return the cumulative sum vector?
#'
#' @return Jx1 cumulative log sum exp vector. 
#' @export 
LogSumExp <- function(x, cum = FALSE) {
    .Call(`_MatrixOps_LogSumExp`, x, cum)
}

